import { ImagesConstants } from "./images.constants";

export const onboarding = {
  prospectiveTenant: [
    {
      id: 1,
      title: "onboarding_1_title",
      subtitle: "onboarding_1_subtitle",
      description: "onboarding_1_desc",
      image: ImagesConstants.WelcomeToWAJ,
    },
    {
      id: 2,
      title: "onboarding_2_title",
      subtitle: "onboarding_2_desc",
      description: "onboarding_2_desc",
      image: ImagesConstants.FindThePerfectPlace,
    },
    {
      id: 3,
      title: "onboarding_3_title",
      subtitle: "onboarding_3_desc",
      description: "onboarding_3_desc",
      image: ImagesConstants.ApplyWithConfidence,
    },
    {
      id: 4,
      title: "onboarding_4_title",
      subtitle: "onboarding_4_desc",
      description: "onboarding_4_desc",
      image: ImagesConstants.ChatWithLandlordsInstantly,
    },
    {
      id: 5,
      title: "onboarding_5_title",
      subtitle: "onboarding_5_desc",
      description: "onboarding_5_desc",
      image: ImagesConstants.StayOnTopOfEverything,
    },
  ],
  tenant: [
    {
      id: 1,
      title: "onboarding_1_title",
      subtitle: "onboarding_1_subtitle",
      description: "onboarding_1_desc",
      image: ImagesConstants.WelcomeToWAJ,
    },
    {
      id: 2,
      title: "onboarding_2_title",
      subtitle: "onboarding_2_desc",
      description: "onboarding_2_desc",
      image: ImagesConstants.FindThePerfectPlace,
    },
    {
      id: 3,
      title: "onboarding_3_title",
      subtitle: "onboarding_3_desc",
      description: "onboarding_3_desc",
      image: ImagesConstants.ApplyWithConfidence,
    },
    {
      id: 4,
      title: "onboarding_4_title",
      subtitle: "onboarding_4_desc",
      description: "onboarding_4_desc",
      image: ImagesConstants.ChatWithLandlordsInstantly,
    },
    {
      id: 5,
      title: "onboarding_5_title",
      subtitle: "onboarding_5_desc",
      description: "onboarding_5_desc",
      image: ImagesConstants.StayOnTopOfEverything,
    },
  ],
  landlord: [
    {
      id: 1,
      title: "onboarding_1_title",
      subtitle: "onboarding_1_subtitle",
      description: "onboarding_1_desc",
      image: ImagesConstants.WelcomeToWAJ,
    },
    {
      id: 2,
      title: "onboarding_2_title",
      subtitle: "onboarding_2_desc",
      description: "onboarding_2_desc",
      image: ImagesConstants.FindThePerfectPlace,
    },
    {
      id: 3,
      title: "onboarding_3_title",
      subtitle: "onboarding_3_desc",
      description: "onboarding_3_desc",
      image: ImagesConstants.ApplyWithConfidence,
    },
    {
      id: 4,
      title: "onboarding_4_title",
      subtitle: "onboarding_4_desc",
      description: "onboarding_4_desc",
      image: ImagesConstants.ChatWithLandlordsInstantly,
    },
    {
      id: 5,
      title: "onboarding_5_title",
      subtitle: "onboarding_5_desc",
      description: "onboarding_5_desc",
      image: ImagesConstants.StayOnTopOfEverything,
    },
  ],
  agent: [
    {
      id: 1,
      title: "onboarding_1_title",
      subtitle: "onboarding_1_subtitle",
      description: "onboarding_1_desc",
      image: ImagesConstants.WelcomeToWAJ,
    },
    {
      id: 2,
      title: "onboarding_2_title",
      subtitle: "onboarding_2_desc",
      description: "onboarding_2_desc",
      image: ImagesConstants.FindThePerfectPlace,
    },
    {
      id: 3,
      title: "onboarding_3_title",
      subtitle: "onboarding_3_desc",
      description: "onboarding_3_desc",
      image: ImagesConstants.ApplyWithConfidence,
    },
    {
      id: 4,
      title: "onboarding_4_title",
      subtitle: "onboarding_4_desc",
      description: "onboarding_4_desc",
      image: ImagesConstants.ChatWithLandlordsInstantly,
    },
    {
      id: 5,
      title: "onboarding_5_title",
      subtitle: "onboarding_5_desc",
      description: "onboarding_5_desc",
      image: ImagesConstants.StayOnTopOfEverything,
    },
  ],
};