import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      welcome: "Welcome to WAJ",
      next: "Next",
      select_role: "To personalize your experience, may I know who you are?",
      prospective_tenant: "Prospective Tenant",
      looking_for_rent: "Looking for a place to rent",
      tenant: "Tenant",
      already_renting: "Already renting a property",
      landlord: "Landlord",
      property_owner: "Property Owner",
      agent: "Agent",
      property_management_agent: "Property management agent",
      onboarding_1_title: "Welcome to Waj",
      onboarding_1_subtitle: "Your next home is just a tap away",
      onboarding_1_desc: "Browse verified listings, connect with landlords, and apply – all in one place.",
      onboarding_2_title: "Find the Perfect Place",
      onboarding_2_desc: "Filter by location, price, and amenities to discover apartments that match your lifestyle.",
      onboarding_3_title: "Apply with Confidence",
      onboarding_3_desc: "Submit your rental application securely, including ID, name, and phone number — no paper, no hassle.",
      onboarding_4_title: "Chat with Landlords Instantly",
      onboarding_4_desc: "Ask questions, schedule viewings, and get real-time updates directly from the property owner.",
      onboarding_5_title: "Stay on Top of Everything",
      onboarding_5_desc: "Track your applications, revisit favorites, and get notified when new listings hit the market.",
      back: "Back",
      get_started: "Get Started",
      get_started_login: "Get Started",
      login_subtitle: "By joining us, you will gain access to cutting-edge resources, expert guidance, etc. Unlock your potential now!",
      email: "Email",
      enter_email: "Enter email",
      password: "Password",
      enter_password: "Enter password",
      remember_me: "Remember me",
      forgot_password: "Forgot password?",
      login: "Login",
      create_account: "Create your free account",
      signup_subtitle: "Let's start your educational journey together, where every step forward is a step towards a brighter future!",
      full_name: "Full Name *",
      email_address: "Email Address *",
      password_required: "Password *",
      confirm_password: "Confirm Password *",
      sign_up: "Sign Up",
      or_continue_with: "or continue with",
      continue_google: "Continue With Google",
      continue_apple: "Continue With Apple",
      continue_nafath: "Continue With Nafath",
      location: "Location",
      location_permission_denied: "Location permission denied.",
      enable_location_services: "Please enable Location Services in device settings.",
      unable_get_location: "Unable to get your current location.",
      fetching_location: "Fetching your location...",
      try_again: "Try Again",
      select_manually: "Select manually instead",
      search_enter_address: "Search or enter address",
      start_typing_search: "Start typing to search for a location...",
      set_location: "Set your location",
      device_location_used: "We’ve used your device location. Adjust the pin if needed.",
      search_map_location: "Search or tap on the map to set your location.",
      confirm: "Confirm",
      verify_email: "Verify your email address",
      sent_code_to: "We have sent you a 5-digit verification code at",
      didnt_receive_code: "Didn’t receive the code?",
      resend_here: "Resend here",
      choose_real_estate_type: "Choose real estate type",
      select_preferable_type: "Select your preferable real estate type below",
      house: "House",
      villa: "Villa",
      apartment: "Apartment",
      workspace: "Workspace",
      cabin: "Cabin",
      cluster: "Cluster",
      lets_get_started: "Let's Get Started!",
      please_select_type: "Please select a type!!",
      permission_required: "Permission Required",
      enable_location_permission: "Please enable location permission for the best experience.",
      error: "Error",
      unable_access_location: "Unable to access location.",
      let_us_know_location: "Let us know your location for best experience",
      allow_google_maps: "Allow Google Maps",
      set_manually: "Set Manually",
    },
  },
  ar: {
    translation: {
      welcome: "مرحبًا بك في WAJ",
      next: "التالي",
      select_role: "لتخصيص تجربتك ، هل يمكنني معرفة من أنت؟",
      prospective_tenant: "مستأجر محتمل",
      looking_for_rent: "أبحث عن مكان للإيجار",
      tenant: "مستأجر",
      already_renting: "مستأجر حالي",
      landlord: "مالك العقار",
      property_owner: "مالك العقار",
      agent: "وكيل",
      property_management_agent: "وكيل إدارة الممتلكات",
      onboarding_1_title: "مرحبًا بك في Waj",
      onboarding_1_subtitle: "منزلك التالي على بعد نقرة واحدة",
      onboarding_1_desc: "تصفح القوائم الموثقة، وتواصل مع الملاك، وقدم طلبك - كل ذلك في مكان واحد.",
      onboarding_2_title: "اعثر على المكان المثالي",
      onboarding_2_desc: "قم بالتصفية حسب الموقع والسعر والمرافق لاكتشاف الشقق التي تناسب نمط حياتك.",
      onboarding_3_title: "قدم طلبك بثقة",
      onboarding_3_desc: "أرسل طلب الإيجار الخاص بك بأمان، بما في ذلك الهوية والاسم ورقم الهاتف - بدون ورق، بدون متاعب.",
      onboarding_4_title: "تحدث مع الملاك فورًا",
      onboarding_4_desc: "اطرح الأسئلة، وحدد مواعيد للمشاهدة، واحصل على تحديثات في الوقت الفعلي مباشرة من مالك العقار.",
      onboarding_5_title: "ابق على اطلاع بكل شيء",
      onboarding_5_desc: "تتبع طلباتك، وراجع المفضلة، واحصل على إشعارات عند طرح قوائم جديدة في السوق.",
      back: "رجوع",
      get_started: "ابدأ الآن",
      get_started_login: "ابدأ الآن",
      login_subtitle: "من خلال الانضمام إلينا، ستتمكن من الوصول إلى أحدث الموارد وتوجيهات الخبراء والمزيد. أطلق العنان لإمكاناتك الآن!",
      email: "البريد الإلكتروني",
      enter_email: "أدخل البريد الإلكتروني",
      password: "كلمة المرور",
      enter_password: "أدخل كلمة المرور",
      remember_me: "تذكرني",
      forgot_password: "هل نسيت كلمة المرور؟",
      login: "تسجيل الدخول",
      create_account: "أنشئ حسابك المجاني",
      signup_subtitle: "لنبدأ رحلتك التعليمية معًا، حيث كل خطوة للأمام هي خطوة نحو مستقبل أكثر إشراقًا!",
      full_name: "الاسم الكامل *",
      email_address: "عنوان البريد الإلكتروني *",
      password_required: "كلمة المرور *",
      confirm_password: "تأكيد كلمة المرور *",
      sign_up: "إنشاء حساب",
      or_continue_with: "أو الاستمرار مع",
      continue_google: "الاستمرار مع Google",
      continue_apple: "الاستمرار مع Apple",
      continue_nafath: "الاستمرار مع نفاذ",
      location: "الموقع",
      location_permission_denied: "تم رفض إذن الموقع.",
      enable_location_services: "يرجى تمكين خدمات الموقع في إعدادات الجهاز.",
      unable_get_location: "غير قادر على الحصول على موقعك الحالي.",
      fetching_location: "جاري جلب موقعك...",
      try_again: "حاول مرة أخرى",
      select_manually: "تحديد يدويًا بدلاً من ذلك",
      search_enter_address: "ابحث أو أدخل العنوان",
      start_typing_search: "ابدأ الكتابة للبحث عن موقع...",
      set_location: "تحديد موقعك",
      device_location_used: "لقد استخدمنا موقع جهازك. اضبط الدبوس إذا لزم الأمر.",
      search_map_location: "ابحث أو اضغط على الخريطة لتحديد موقعك.",
      confirm: "تأكيد",
      verify_email: "تحقق من عنوان بريدك الإلكتروني",
      sent_code_to: "لقد أرسلنا لك رمز تحقق مكون من 5 أرقام إلى",
      didnt_receive_code: "لم تستلم الرمز؟",
      resend_here: "أعد الإرسال هنا",
      choose_real_estate_type: "اختر نوع العقار",
      select_preferable_type: "حدد نوع العقار المفضل لديك أدناه",
      house: "منزل",
      villa: "فيلا",
      apartment: "شقة",
      workspace: "مساحة عمل",
      cabin: "كوخ",
      cluster: "مجمع",
      lets_get_started: "هيا بنا نبدأ!",
      please_select_type: "يرجى اختيار نوع!!",
      permission_required: "الإذن مطلوب",
      enable_location_permission: "يرجى تمكين إذن الموقع للحصول على أفضل تجربة.",
      error: "خطأ",
      unable_access_location: "غير قادر على الوصول إلى الموقع.",
      let_us_know_location: "أخبرنا بموقعك للحصول على أفضل تجربة",
      allow_google_maps: "السماح بخرائط Google",
      set_manually: "تحديد يدويًا",
    },
  },
};

// ✅ Fix for EXPO 2025 (Localization doesn't have .locale — use getLocales())
const getDeviceLang = () => {
  const locales = Localization.getLocales();
  if (locales && locales.length > 0) {
    return locales[0].languageCode ?? "en";
  }
  return "en";
};

export const initLanguage = async () => {
  const savedLang = await AsyncStorage.getItem("appLanguage");
  const lng = savedLang || getDeviceLang();

  i18n.use(initReactI18next).init({
    lng,
    fallbackLng: "en",
    resources,
    interpolation: { escapeValue: false },
  });
};

export default i18n;
