import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      welcome: "Welcome to WAJ",
      next: "Next",
      select_role: "To personalize your experience, may I know who you are?",
      prospective_tenant: "Prospective Tenant",
      looking_for_rent: "Looking for a place to rent",
      tenant: "Tenant",
      already_renting: "Already renting a property",
      landlord: "Landlord",
      property_owner: "Property Owner",
      agent: "Agent",
      property_management_agent: "Property management agent",
      onboarding_1_title: "Welcome to Waj",
      onboarding_1_subtitle: "Your next home is just a tap away",
      onboarding_1_desc:
        "Browse verified listings, connect with landlords, and apply – all in one place.",
      onboarding_2_title: "Find the Perfect Place",
      onboarding_2_desc:
        "Filter by location, price, and amenities to discover apartments that match your lifestyle.",
      onboarding_3_title: "Apply with Confidence",
      onboarding_3_desc:
        "Submit your rental application securely, including ID, name, and phone number — no paper, no hassle.",
      onboarding_4_title: "Chat with Landlords Instantly",
      onboarding_4_desc:
        "Ask questions, schedule viewings, and get real-time updates directly from the property owner.",
      onboarding_5_title: "Stay on Top of Everything",
      onboarding_5_desc:
        "Track your applications, revisit favorites, and get notified when new listings hit the market.",
      back: "Back",
      get_started: "Get Started",
      get_started_login: "Get Started",
      login_subtitle:
        "By joining us, you will gain access to cutting-edge resources, expert guidance, etc. Unlock your potential now!",
      email: "Email",
      enter_email: "Enter email",
      password: "Password",
      enter_password: "Enter password",
      remember_me: "Remember me",
      forgot_password: "Forgot password?",
      login: "Login",
      create_account: "Create your free account",
      signup_subtitle:
        "Let's start your educational journey together, where every step forward is a step towards a brighter future!",
      full_name: "Full Name *",
      email_address: "Email Address *",
      password_required: "Password *",
      confirm_password: "Confirm Password *",
      sign_up: "Sign Up",
      or_continue_with: "or continue with",
      continue_google: "Continue With Google",
      continue_apple: "Continue With Apple",
      continue_nafath: "Continue With Nafath",
      location: "Location",
      location_permission_denied: "Location permission denied.",
      enable_location_services:
        "Please enable Location Services in device settings.",
      unable_get_location: "Unable to get your current location.",
      fetching_location: "Fetching your location...",
      try_again: "Try Again",
      select_manually: "Select manually instead",
      search_enter_address: "Search or enter address",
      start_typing_search: "Start typing to search for a location...",
      set_location: "Set your location",
      device_location_used:
        "We’ve used your device location. Adjust the pin if needed.",
      search_map_location: "Search or tap on the map to set your location.",
      confirm: "Confirm",
      verify_email: "Verify your email address",
      sent_code_to: "We have sent you a 5-digit verification code at",
      didnt_receive_code: "Didn’t receive the code?",
      resend_here: "Resend here",
      choose_real_estate_type: "Choose real estate type",
      select_preferable_type: "Select your preferable real estate type below",
      house: "House",
      villa: "Villa",
      apartment: "Apartment",
      workspace: "Workspace",
      cabin: "Cabin",
      cluster: "Cluster",
      lets_get_started: "Let's Get Started!",
      please_select_type: "Please select a type!!",
      permission_required: "Permission Required",
      enable_location_permission:
        "Please enable location permission for the best experience.",
      error: "Error",
      unable_access_location: "Unable to access location.",
      let_us_know_location: "Let us know your location for best experience",
      allow_google_maps: "Allow Google Maps",
      set_manually: "Set Manually",
      // Prospective Tenant
      explore: "Explore",
      search_anything: "Search anything",
      featured: "Featured",

      // Profile
      profile: "Profile",
      general: "General",
      language: "Language",
      theme: "Theme",
      dark_mode: "Dark Mode",
      notifications: "Notifications",
      allow_sms: "Allow SMS",
      allow_email_notification: "Allow Email Notification",
      forget_password: "Forget Password",
      danger_zone: "Danger Zone",
      delete_account_warning:
        "Once you delete your account, there is no going back.",
      delete_account: "Delete Account",
      sign_out: "Sign Out",
      restart_required: "Restart required to apply changes.",
      language_changed: "Language changed!",
      restart: "Restart",
      cancel: "Cancel",

      // Tenant Home
      home: "Home",
      month: "/month",
      guest: "Guest",
      bedrooms: "Bedrooms",
      baths: "Baths",
      reviews: "Reviews",
      contact_person: "Contact Person",
      information: "Information",
      next_payment: "Next Payment",
      payment_term: "Payment Term",
      lease_duration: "Lease Duration",
      size: "Size",
      services: "Services",
      pay_rent: "Pay Rent",
      service: "Service",
      lease: "Lease",
      pending_tasks: "Pending Tasks",
      in_progress: "In Progress",
      pending: "Pending",
      complete: "Complete",
      view: "View",
      next_payment_due: "Next Payment Due",
      upload_payment_receipt: "Upload Payment Receipt",
      payment_history: "Payment History",
      paid_on: "Paid on",
      download: "Download",
      verified: "VERIFIED",

      // Landlord Home
      welcome_back: "Welcome Back!",
      property_overview: "Here's your property overview.",
      total_properties: "Total Properties",
      active_listings: "Active Listings",
      occupancy_rate: "Occupancy Rate",
      monthly_revenue: "Monthly Revenue",
      pending_listings: "Pending Listings",
      my_tenant: "My Tenant",
      see_all: "See All",
      due_payment: "Due Payment",
      recent_applications: "Recent Applications",
      service_requests: "Service Requests",
      updates_tips: "Updates & Tips",
      receipt_released: "Receipt Released",
      receipt_released_msg: "Your receipt has been released",
      payment_success: "Payment Success",
      payment_success_msg: "Your payment has been successfully",
      rent_canceled: "Rent Canceled",
      rent_canceled_msg: "Your cancel request has been received",
      pending_rent: "Pending Rent",
      pending_rent_msg: "Your rent has been delayed",

      // Landlord Dashboard
      analytical_dashboard: "Analytical Dashboard",
      property_analytics: "Property Analytics",
      see_more: "See more",
      avg_rent_unit: "Avg Rent/Unit",
      collection_rate: "Collection Rate",
      operational_dashboard: "Operational Dashboard",
      work_orders_complete: "Work Orders Complete",
      avg_response_time: "Avg Response Time",
      tenant_experience: "Tenant Experience",
      satisfaction_score: "Satisfaction Score",
      retention_rate: "Retention Rate",
      renewal_ratio: "Renewal Ratio",
      complaints_tenant: "Complaints/Tenant",
      digital_engagement: "Digital Engagement",
      portfolio_overview: "Portfolio Overview",
      portfolio_occupancy: "Portfolio Occupancy",
      revenue_per_sqft: "Revenue per Sq.Ft",
      add_information: "Add Information",
      upload_file: "Upload File",
      or: "Or",
      add_manually: "Add Manually",
      vs_last_month: "vs last month",
      out_of_10: "out of 10",
      twelve_month_average: "12-month average",
      renewals_vs_new: "renewals vs new",
      per_month: "per month",
      active_users: "active users",

      // Agent
      favorite: "Favorite",
      chat: "Chat",

      // Components
      phone_number: "Phone Number",
      country: "Country",
      select_country_flag: "(Select at flag to choose your country)",
      id_number: "ID",
      nationality: "Nationality",
      employment_status: "Employment Status",
      expired_date: "Expired Date",
      purpose: "Purpose",
      na: "N/A",
      about: "About",
      listed_property: "Listed Property",
      about_owner_placeholder:
        "Meet Steven Adams, the owner of this charming townhouse located in Brooklyn's Park Slope neighborhood...",
      set_new_location: "Set New Location",

      // Button Texts
      add_review: "Add Review",
      apply_filter: "Apply Filter",
      back_to_home: "Back to Home",
      continue: "Continue",
      submit: "Submit",
      new_request: "New Request",
      save_changes: "Save Changes",
      book_now: "Book Now",
      send_request: "Send Request",
      request: "Request",
      apply: "Apply",

      // Review
      please_select_rating: "Please select your rating",
      please_write_feedback: "Please write your feedback",
      tell_us_more: "Tell us more...",
      add_image: "Add Image",

      // Filter
      filter: "Filter",
      property_type: "Property Type",
      all: "All",
      price_range: "Price Range",
      min: "Min",
      max: "Max",
      additional_filters: "Additional Filters",
      rental_term: "Rental Term",
      bedrooms_min: "Bedrooms (min)",
      bathrooms_min: "Bathrooms (min)",
      city: "City",
      district: "District",
      zip_code: "Zip Code",
      furnishing: "Furnishing",
      pets_allowed: "Pets Allowed",
      available_from: "Available From",
      select_date: "Select Date",
      amenities: "Amenities",
      security_features: "Security Features",
      select: "Select",

      // House Details
      description: "Description",
      photo: "Photo",
      //   property_owner: "Property Owner",

      // Search
      search: "Search",
      recent_search: "Recent Search",

      // Applications
      viewing_requests: "Viewing Requests",
      rental_applications: "Rental Applications",
      my_applications: "My Applications",
      approved: "Approved",
      rejected: "Rejected",

      // Appointment
      select_date_appointment: "Select Date",
      desired_move_in_date: "Desired Move-in Date",
      lease_duration_months: "Lease Duration (months)",
      your_phone_number: "Your phone number",
      your_email: "Your email",
      name: "Name",
      monthly: "Monthly",
      quarterly: "Quarterly",
      yearly: "Yearly",
      rent: "Rent",
      business: "Business",
      other: "Other",

      // Add Properties
      add_properties: "Add Properties",
      property_title: "Property title",
      monthly_rent: "Monthly rent",
      area_sqm: "Area (sqm)",
      status: "Status",
      available: "Available",
      rented: "Rented",
      under_maintenance: "Under Maintenance",
      furnished: "Furnished",
      semi_furnished: "Semi-furnished",
      unfurnished: "Unfurnished",
      allowed: "Allowed",
      not_allowed: "Not Allowed",
      upload_photo: "Upload Photo",
      validation_enter_title: "Please enter property title.",
      success_property_ready: "Property object is ready (check console).",
      permission_required_photos:
        "We need access to your photos to upload property images.",
      camera_permission_required: "Camera permission required",

      // Appointment Success
      you_are_done: "You're done!",
      thanks_choosing_platform:
        "Thanks for choosing our platform, all the best for you",
      appointment_success: "Appointment Success!",
      appointment_completed:
        "You've completed the appointment process, you can see your appointment detail below",
      hope_pleasant_experience: "Hope you have a pleasant experience!",

      // Application Details
      applied: "Applied",
      desired_move_in_date_label: "Desired Move-in Date",
      cancel_appointment: "Cancel Appointment",
      photos: "Photos",

      // Chat Detail
      today: "Today",
      write_message: "Write a message ...",

      // Notification
      notification: "Notification",

      // Photo Details
      all_photos: "All Photos",
      parking_lot: "Parking Lot",
      living_room: "Living Room",
      washroom: "Washroom",
      content_appears_here: "content appears here...",

      // Profile Details
      profile_detail: "Profile Detail",
    },
  },
  ar: {
    translation: {
      welcome: "مرحبًا بك في WAJ",
      next: "التالي",
      select_role: "لتخصيص تجربتك ، هل يمكنني معرفة من أنت؟",
      prospective_tenant: "مستأجر محتمل",
      looking_for_rent: "أبحث عن مكان للإيجار",
      tenant: "مستأجر",
      already_renting: "مستأجر حالي",
      landlord: "مالك العقار",
      property_owner: "مالك العقار",
      agent: "وكيل",
      property_management_agent: "وكيل إدارة الممتلكات",
      onboarding_1_title: "مرحبًا بك في Waj",
      onboarding_1_subtitle: "منزلك التالي على بعد نقرة واحدة",
      onboarding_1_desc:
        "تصفح القوائم الموثقة، وتواصل مع الملاك، وقدم طلبك - كل ذلك في مكان واحد.",
      onboarding_2_title: "اعثر على المكان المثالي",
      onboarding_2_desc:
        "قم بالتصفية حسب الموقع والسعر والمرافق لاكتشاف الشقق التي تناسب نمط حياتك.",
      onboarding_3_title: "قدم طلبك بثقة",
      onboarding_3_desc:
        "أرسل طلب الإيجار الخاص بك بأمان، بما في ذلك الهوية والاسم ورقم الهاتف - بدون ورق، بدون متاعب.",
      onboarding_4_title: "تحدث مع الملاك فورًا",
      onboarding_4_desc:
        "اطرح الأسئلة، وحدد مواعيد للمشاهدة، واحصل على تحديثات في الوقت الفعلي مباشرة من مالك العقار.",
      onboarding_5_title: "ابق على اطلاع بكل شيء",
      onboarding_5_desc:
        "تتبع طلباتك، وراجع المفضلة، واحصل على إشعارات عند طرح قوائم جديدة في السوق.",
      back: "رجوع",
      get_started: "ابدأ الآن",
      get_started_login: "ابدأ الآن",
      login_subtitle:
        "من خلال الانضمام إلينا، ستتمكن من الوصول إلى أحدث الموارد وتوجيهات الخبراء والمزيد. أطلق العنان لإمكاناتك الآن!",
      email: "البريد الإلكتروني",
      enter_email: "أدخل البريد الإلكتروني",
      password: "كلمة المرور",
      enter_password: "أدخل كلمة المرور",
      remember_me: "تذكرني",
      forgot_password: "هل نسيت كلمة المرور؟",
      login: "تسجيل الدخول",
      create_account: "أنشئ حسابك المجاني",
      signup_subtitle:
        "لنبدأ رحلتك التعليمية معًا، حيث كل خطوة للأمام هي خطوة نحو مستقبل أكثر إشراقًا!",
      full_name: "الاسم الكامل *",
      email_address: "عنوان البريد الإلكتروني *",
      password_required: "كلمة المرور *",
      confirm_password: "تأكيد كلمة المرور *",
      sign_up: "إنشاء حساب",
      or_continue_with: "أو الاستمرار مع",
      continue_google: "الاستمرار مع Google",
      continue_apple: "الاستمرار مع Apple",
      continue_nafath: "الاستمرار مع نفاذ",
      location: "الموقع",
      location_permission_denied: "تم رفض إذن الموقع.",
      enable_location_services: "يرجى تمكين خدمات الموقع في إعدادات الجهاز.",
      unable_get_location: "غير قادر على الحصول على موقعك الحالي.",
      fetching_location: "جاري جلب موقعك...",
      try_again: "حاول مرة أخرى",
      select_manually: "تحديد يدويًا بدلاً من ذلك",
      search_enter_address: "ابحث أو أدخل العنوان",
      start_typing_search: "ابدأ الكتابة للبحث عن موقع...",
      set_location: "تحديد موقعك",
      device_location_used:
        "لقد استخدمنا موقع جهازك. اضبط الدبوس إذا لزم الأمر.",
      search_map_location: "ابحث أو اضغط على الخريطة لتحديد موقعك.",
      confirm: "تأكيد",
      verify_email: "تحقق من عنوان بريدك الإلكتروني",
      sent_code_to: "لقد أرسلنا لك رمز تحقق مكون من 5 أرقام إلى",
      didnt_receive_code: "لم تستلم الرمز؟",
      resend_here: "أعد الإرسال هنا",
      choose_real_estate_type: "اختر نوع العقار",
      select_preferable_type: "حدد نوع العقار المفضل لديك أدناه",
      house: "منزل",
      villa: "فيلا",
      apartment: "شقة",
      workspace: "مساحة عمل",
      cabin: "كوخ",
      cluster: "مجمع",
      lets_get_started: "هيا بنا نبدأ!",
      please_select_type: "يرجى اختيار نوع!!",
      permission_required: "الإذن مطلوب",
      enable_location_permission:
        "يرجى تمكين إذن الموقع للحصول على أفضل تجربة.",
      error: "خطأ",
      unable_access_location: "غير قادر على الوصول إلى الموقع.",
      let_us_know_location: "أخبرنا بموقعك للحصول على أفضل تجربة",
      allow_google_maps: "السماح بخرائط Google",
      set_manually: "تحديد يدويًا",

      // Prospective Tenant
      explore: "استكشف",
      search_anything: "ابحث عن أي شيء",
      featured: "مميز",

      // Profile
      profile: "الملف الشخصي",
      general: "عام",
      language: "اللغة",
      theme: "المظهر",
      dark_mode: "الوضع الداكن",
      notifications: "الإشعارات",
      allow_sms: "السماح بالرسائل القصيرة",
      allow_email_notification: "السماح بإشعارات البريد الإلكتروني",
      forget_password: "نسيت كلمة المرور",
      danger_zone: "منطقة الخطر",
      delete_account_warning: "بمجرد حذف حسابك، لا يمكن التراجع عن ذلك.",
      delete_account: "حذف الحساب",
      sign_out: "تسجيل الخروج",
      restart_required: "مطلوب إعادة التشغيل لتطبيق التغييرات.",
      language_changed: "تم تغيير اللغة!",
      restart: "إعادة تشغيل",
      cancel: "إلغاء",

      // Tenant Home
      home: "الرئيسية",
      month: "/شهر",
      guest: "ضيف",
      bedrooms: "غرف نوم",
      baths: "حمامات",
      reviews: "مراجعات",
      contact_person: "شخص الاتصال",
      information: "معلومات",
      next_payment: "الدفعة التالية",
      payment_term: "مدة الدفع",
      lease_duration: "مدة الإيجار",
      size: "المساحة",
      services: "الخدمات",
      pay_rent: "دفع الإيجار",
      service: "خدمة",
      lease: "عقد إيجار",
      pending_tasks: "المهام المعلقة",
      in_progress: "قيد التنفيذ",
      pending: "معلق",
      complete: "مكتمل",
      view: "عرض",
      next_payment_due: "الدفعة التالية المستحقة",
      upload_payment_receipt: "تحميل إيصال الدفع",
      payment_history: "سجل الدفع",
      paid_on: "تم الدفع في",
      download: "تحميل",
      verified: "موثق",

      // Landlord Home
      welcome_back: "مرحبًا بعودتك!",
      property_overview: "إليك نظرة عامة على ممتلكاتك.",
      total_properties: "إجمالي العقارات",
      active_listings: "القوائم النشطة",
      occupancy_rate: "معدل الإشغال",
      monthly_revenue: "الإيرادات الشهرية",
      pending_listings: "القوائم المعلقة",
      my_tenant: "مستأجري",
      see_all: "عرض الكل",
      due_payment: "الدفعة المستحقة",
      recent_applications: "الطلبات الأخيرة",
      service_requests: "طلبات الخدمة",
      updates_tips: "تحديثات ونصائح",
      receipt_released: "تم إصدار الإيصال",
      receipt_released_msg: "تم إصدار إيصالك",
      payment_success: "تم الدفع بنجاح",
      payment_success_msg: "تم الدفع بنجاح",
      rent_canceled: "تم إلغاء الإيجار",
      rent_canceled_msg: "تم استلام طلب الإلغاء الخاص بك",
      pending_rent: "إيجار معلق",
      pending_rent_msg: "تم تأخير إيجارك",

      // Landlord Dashboard
      analytical_dashboard: "لوحة التحكم التحليلية",
      property_analytics: "تحليلات العقارات",
      see_more: "شاهد المزيد",
      avg_rent_unit: "متوسط الإيجار/الوحدة",
      collection_rate: "معدل التحصيل",
      operational_dashboard: "لوحة التحكم التشغيلية",
      work_orders_complete: "أوامر العمل المكتملة",
      avg_response_time: "متوسط وقت الاستجابة",
      tenant_experience: "تجربة المستأجر",
      satisfaction_score: "درجة الرضا",
      retention_rate: "معدل الاحتفاظ",
      renewal_ratio: "نسبة التجديد",
      complaints_tenant: "شكاوى/مستأجر",
      digital_engagement: "المشاركة الرقمية",
      portfolio_overview: "نظرة عامة على المحفظة",
      portfolio_occupancy: "إشغال المحفظة",
      revenue_per_sqft: "الإيرادات لكل قدم مربع",
      add_information: "إضافة معلومات",
      upload_file: "رفع ملف",
      or: "أو",
      add_manually: "إضافة يدويًا",
      vs_last_month: "مقابل الشهر الماضي",
      out_of_10: "من 10",
      twelve_month_average: "متوسط 12 شهرًا",
      renewals_vs_new: "التجديدات مقابل الجديد",
      per_month: "في الشهر",
      active_users: "المستخدمين النشطين",

      // Agent
      favorite: "مفضل",
      chat: "دردشة",

      // Components
      phone_number: "رقم الهاتف",
      country: "الدولة",
      select_country_flag: "(اختر العلم لتحديد دولتك)",
      id_number: "رقم الهوية",
      nationality: "الجنسية",
      employment_status: "الحالة الوظيفية",
      expired_date: "تاريخ الانتهاء",
      purpose: "الغرض",
      na: "غير متوفر",
      about: "حول",
      listed_property: "العقار المدرج",
      about_owner_placeholder:
        "تعرف على ستيفن آدامز، مالك هذا المنزل الريفي الساحر الواقع في حي بارك سلوب في بروكلين...",
      set_new_location: "تحديد موقع جديد",

      // Button Texts
      add_review: "إضافة مراجعة",
      apply_filter: "تطبيق الفلتر",
      back_to_home: "العودة للرئيسية",
      continue: "متابعة",
      submit: "إرسال",
      new_request: "طلب جديد",
      save_changes: "حفظ التغييرات",
      book_now: "احجز الآن",
      send_request: "إرسال الطلب",
      request: "طلب",
      apply: "تطبيق",

      // Review
      please_select_rating: "يرجى اختيار تقييمك",
      please_write_feedback: "يرجى كتابة ملاحظاتك",
      tell_us_more: "أخبرنا المزيد...",
      add_image: "إضافة صورة",

      // Filter
      filter: "فلتر",
      property_type: "نوع العقار",
      all: "الكل",
      price_range: "نطاق السعر",
      min: "الحد الأدنى",
      max: "الحد الأقصى",
      additional_filters: "فلاتر إضافية",
      rental_term: "مدة الإيجار",
      bedrooms_min: "غرف النوم (الحد الأدنى)",
      bathrooms_min: "الحمامات (الحد الأدنى)",
      city: "المدينة",
      district: "الحي",
      zip_code: "الرمز البريدي",
      furnishing: "التأثيث",
      pets_allowed: "السماح بالحيوانات الأليفة",
      available_from: "متاح من",
      select_date: "اختر التاريخ",
      amenities: "المرافق",
      security_features: "ميزات الأمان",
      select: "اختر",

      // House Details
      description: "الوصف",
      photo: "الصور",
      //   property_owner: "مالك العقار",

      // Search
      search: "بحث",
      recent_search: "البحث الأخير",

      // Applications
      viewing_requests: "طلبات المشاهدة",
      rental_applications: "طلبات الإيجار",
      my_applications: "طلباتي",
      approved: "موافق عليه",
      rejected: "مرفوض",

      // Appointment
      select_date_appointment: "اختر التاريخ",
      desired_move_in_date: "تاريخ الانتقال الم desired",
      lease_duration_months: "مدة الإيجار (بالأشهر)",
      your_phone_number: "رقم هاتفك",
      your_email: "بريدك الإلكتروني",
      name: "الاسم",
      monthly: "شهري",
      quarterly: "ربع سنوي",
      yearly: "سنوي",
      rent: "إيجار",
      business: "تجاري",
      other: "أخرى",

      // Add Properties
      add_properties: "إضافة عقارات",
      property_title: "عنوان العقار",
      monthly_rent: "الإيجار الشهري",
      area_sqm: "المساحة (متر مربع)",
      status: "الحالة",
      available: "متاح",
      rented: "مؤجر",
      under_maintenance: "قيد الصيانة",
      furnished: "مؤثث",
      semi_furnished: "شبه مؤثث",
      unfurnished: "غير مؤثث",
      allowed: "مسموح",
      not_allowed: "غير مسموح",
      upload_photo: "رفع صورة",
      validation_enter_title: "يرجى إدخال عنوان العقار.",
      success_property_ready: "كائن العقار جاهز (تحقق من وحدة التحكم).",
      permission_required_photos: "نحتاج إلى الوصول إلى صورك لرفع صور العقار.",
      camera_permission_required: "إذن الكاميرا مطلوب",

      // Appointment Success
      you_are_done: "لقد انتهيت!",
      thanks_choosing_platform: "شكرًا لاختيارك منصتنا، كل التوفيق لك",
      appointment_success: "نجح الموعد!",
      appointment_completed:
        "لقد أكملت عملية الموعد، يمكنك رؤية تفاصيل موعدك أدناه",
      hope_pleasant_experience: "نأمل أن تكون تجربتك ممتعة!",

      // Application Details
      applied: "تم التقديم",
      desired_move_in_date_label: "تاريخ الانتقال الم desired",
      cancel_appointment: "إلغاء الموعد",
      photos: "الصور",

      // Chat Detail
      today: "اليوم",
      write_message: "اكتب رسالة ...",

      // Notification
      notification: "الإشعارات",

      // Photo Details
      all_photos: "جميع الصور",
      parking_lot: "موقف السيارات",
      living_room: "غرفة المعيشة",
      washroom: "الحمام",
      content_appears_here: "يظهر المحتوى هنا...",

      // Profile Details
      profile_detail: "تفاصيل الملف الشخصي",
    },
  },
};

// ✅ Fix for EXPO 2025 (Localization doesn't have .locale — use getLocales())
const getDeviceLang = () => {
  const locales = Localization.getLocales();
  if (locales && locales.length > 0) {
    return locales[0].languageCode ?? "en";
  }
  return "en";
};

export const initLanguage = async () => {
  const savedLang = await AsyncStorage.getItem("appLanguage");
  const lng = savedLang || getDeviceLang();

  i18n.use(initReactI18next).init({
    lng,
    fallbackLng: "en",
    resources,
    interpolation: { escapeValue: false },
  });
};

export default i18n;
